[env:adafruit_feather_esp32c6]
platform  = espressif32
board     = adafruit_feather_esp32c6
framework = arduino

monitor_speed   = 115200
upload_port     = /dev/cu.usbmodem2101
monitor_port    = /dev/cu.usbmodem2101
monitor_filters = esp32_exception_decoder
upload_speed    = 921600

; USB-CDC serial (built-in on ESP32-C6)
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    bblanchon/ArduinoJson@^7.3.0
